#!/bin/bash

echo "Hello gh-interactive-branch-checkout!"

BRANCHES=()
let ctr=0
eval $(git for-each-ref --count=10 --no-merged --sort=-committerdate --format='BRANCHES+=(%(refname:short))' refs/)

run=true
while( $run ); do
  let ctr=1
  while [ $ctr -le ${#BRANCHES[@]} ]; do
    echo "--- $ctr. ${BRANCHES[$ctr-1]}"
    let ctr++
  done

  echo -n "Enter number of branch(es) to delete, enter 'Q' to quit [Q/#]: "
  read -a checkout
  checkout=${checkout:-Q}
  echo ""

  if [ ${checkout[0]} = "Q" ] || [ ${checkout[0]} = "q" ]; then
    exit 0
  fi

  let ctr=1
  for i in ${checkout[@]}; do
    echo "-- $ctr. ${BRANCHES[$i-1]}"
    let ctr++
  done

  echo -n "Really checkout the these branches? [Y/n]: "
  read confirm
  confirm=${confirm:-Y}
  echo "$confirm"

  if [ $confirm = "Y" ] || [ $confirm = "y" ]; then
    for i in ${checkout[@]}; do
      cmd=`echo ${BRANCHES[$i-1]} | awk '{gsub("origin/", ""); print "git checkout "$0}'`
      echo $cmd
      echo $cmd | /bin/sh
      unset BRANCHES[$i-1]
    done
    echo ""
  fi
  BRANCHES=( "${BRANCHES[@]}" )
done
